// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartChair.proto

package com.wen.proto;

public final class SmartChairProto {
  private SmartChairProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.wen.proto.MSG_TYPE}
   */
  public enum MSG_TYPE
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>PING = 0;</code>
     */
    PING(0),
    /**
     * <code>LOGIN = 1;</code>
     */
    LOGIN(1),
    /**
     * <code>HEART = 2;</code>
     */
    HEART(2),
    /**
     * <code>PAY = 3;</code>
     */
    PAY(3),
    /**
     * <code>FINISH = 4;</code>
     */
    FINISH(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PING = 0;</code>
     */
    public static final int PING_VALUE = 0;
    /**
     * <code>LOGIN = 1;</code>
     */
    public static final int LOGIN_VALUE = 1;
    /**
     * <code>HEART = 2;</code>
     */
    public static final int HEART_VALUE = 2;
    /**
     * <code>PAY = 3;</code>
     */
    public static final int PAY_VALUE = 3;
    /**
     * <code>FINISH = 4;</code>
     */
    public static final int FINISH_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MSG_TYPE valueOf(int value) {
      return forNumber(value);
    }

    public static MSG_TYPE forNumber(int value) {
      switch (value) {
        case 0: return PING;
        case 1: return LOGIN;
        case 2: return HEART;
        case 3: return PAY;
        case 4: return FINISH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MSG_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MSG_TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MSG_TYPE>() {
            public MSG_TYPE findValueByNumber(int number) {
              return MSG_TYPE.forNumber(number);
            }
          };

    private final int value;

    private MSG_TYPE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.wen.proto.MSG_TYPE)
  }

  public interface MsgInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wen.proto.MsgInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
     */
    int getMsgTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
     */
    MSG_TYPE getMsgType();

    /**
     * <pre>
     *设备码
     * </pre>
     *
     * <code>string imei = 2;</code>
     */
    String getImei();
    /**
     * <pre>
     *设备码
     * </pre>
     *
     * <code>string imei = 2;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>uint32 info = 3;</code>
     */
    int getInfo();
  }
  /**
   * <pre>
   *命令字：result
   * </pre>
   *
   * Protobuf type {@code com.wen.proto.MsgInfo}
   */
  public  static final class MsgInfo extends
      com.google.protobuf.GeneratedMessageLite<
          MsgInfo, MsgInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:com.wen.proto.MsgInfo)
      MsgInfoOrBuilder {
    private MsgInfo() {
      imei_ = "";
    }
    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
     */
    public MSG_TYPE getMsgType() {
      MSG_TYPE result = MSG_TYPE.forNumber(msgType_);
      return result == null ? MSG_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
     */
    private void setMsgTypeValue(int value) {
        msgType_ = value;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
     */
    private void setMsgType(MSG_TYPE value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msgType_ = value.getNumber();
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
     */
    private void clearMsgType() {
      
      msgType_ = 0;
    }

    public static final int IMEI_FIELD_NUMBER = 2;
    private String imei_;
    /**
     * <pre>
     *设备码
     * </pre>
     *
     * <code>string imei = 2;</code>
     */
    public String getImei() {
      return imei_;
    }
    /**
     * <pre>
     *设备码
     * </pre>
     *
     * <code>string imei = 2;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(imei_);
    }
    /**
     * <pre>
     *设备码
     * </pre>
     *
     * <code>string imei = 2;</code>
     */
    private void setImei(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imei_ = value;
    }
    /**
     * <pre>
     *设备码
     * </pre>
     *
     * <code>string imei = 2;</code>
     */
    private void clearImei() {
      
      imei_ = getDefaultInstance().getImei();
    }
    /**
     * <pre>
     *设备码
     * </pre>
     *
     * <code>string imei = 2;</code>
     */
    private void setImeiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imei_ = value.toStringUtf8();
    }

    public static final int INFO_FIELD_NUMBER = 3;
    private int info_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>uint32 info = 3;</code>
     */
    public int getInfo() {
      return info_;
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>uint32 info = 3;</code>
     */
    private void setInfo(int value) {
      
      info_ = value;
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>uint32 info = 3;</code>
     */
    private void clearInfo() {
      
      info_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != MSG_TYPE.PING.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      if (!imei_.isEmpty()) {
        output.writeString(2, getImei());
      }
      if (info_ != 0) {
        output.writeUInt32(3, info_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != MSG_TYPE.PING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (!imei_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getImei());
      }
      if (info_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, info_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static MsgInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MsgInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MsgInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MsgInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MsgInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MsgInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MsgInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static MsgInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static MsgInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static MsgInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static MsgInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static MsgInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *命令字：result
     * </pre>
     *
     * Protobuf type {@code com.wen.proto.MsgInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          MsgInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wen.proto.MsgInfo)
        MsgInfoOrBuilder {
      // Construct using com.wen.proto.SmartChairProto.MsgInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
       */
      public int getMsgTypeValue() {
        return instance.getMsgTypeValue();
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
       */
      public Builder setMsgTypeValue(int value) {
        copyOnWrite();
        instance.setMsgTypeValue(value);
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
       */
      public MSG_TYPE getMsgType() {
        return instance.getMsgType();
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
       */
      public Builder setMsgType(MSG_TYPE value) {
        copyOnWrite();
        instance.setMsgType(value);
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.wen.proto.MSG_TYPE msg_type = 1;</code>
       */
      public Builder clearMsgType() {
        copyOnWrite();
        instance.clearMsgType();
        return this;
      }

      /**
       * <pre>
       *设备码
       * </pre>
       *
       * <code>string imei = 2;</code>
       */
      public String getImei() {
        return instance.getImei();
      }
      /**
       * <pre>
       *设备码
       * </pre>
       *
       * <code>string imei = 2;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        return instance.getImeiBytes();
      }
      /**
       * <pre>
       *设备码
       * </pre>
       *
       * <code>string imei = 2;</code>
       */
      public Builder setImei(
          String value) {
        copyOnWrite();
        instance.setImei(value);
        return this;
      }
      /**
       * <pre>
       *设备码
       * </pre>
       *
       * <code>string imei = 2;</code>
       */
      public Builder clearImei() {
        copyOnWrite();
        instance.clearImei();
        return this;
      }
      /**
       * <pre>
       *设备码
       * </pre>
       *
       * <code>string imei = 2;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setImeiBytes(value);
        return this;
      }

      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>uint32 info = 3;</code>
       */
      public int getInfo() {
        return instance.getInfo();
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>uint32 info = 3;</code>
       */
      public Builder setInfo(int value) {
        copyOnWrite();
        instance.setInfo(value);
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>uint32 info = 3;</code>
       */
      public Builder clearInfo() {
        copyOnWrite();
        instance.clearInfo();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wen.proto.MsgInfo)
    }
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new MsgInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          MsgInfo other = (MsgInfo) arg1;
          msgType_ = visitor.visitInt(msgType_ != 0, msgType_,    other.msgType_ != 0, other.msgType_);
          imei_ = visitor.visitString(!imei_.isEmpty(), imei_,
              !other.imei_.isEmpty(), other.imei_);
          info_ = visitor.visitInt(info_ != 0, info_,
              other.info_ != 0, other.info_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  msgType_ = rawValue;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  imei_ = s;
                  break;
                }
                case 24: {

                  info_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (MsgInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.wen.proto.MsgInfo)
    private static final MsgInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static MsgInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MsgInfo> PARSER;

    public static com.google.protobuf.Parser<MsgInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
